### PR TITLE
IPFS Pubsub Room: version update

### PR DESCRIPTION
**Pull request by AquiGorka**
Reference: https://github.com/ipfs-shipyard/ipfs-pubsub-room/commit/852d0fa37a1da3414f7cf4a73db8701cef343067

### CODE REVIEW

**Comment by harrshasri** [comment]
Please Update This

**Comment by AquiGorka** [comment]
@hacdias hello, since you are the last committer on this repo I'm pinging you to find out if this is good enough to merge.

**Comment by harrshasri** [comment]
I think so. I was struggling to find out why ipfs is not discovering the peers when updated to 28.2
Now I got to know it is because of the interface update from dial to dialProtocol.

It could be a single word.  But CRITICAL

**Comment by AquiGorka** [comment]
Yep. @harrshasri you are correct. That is exactly why I submitted this PR.

**Comment by lidel** [comment]
cc @pgte, as I am not familiar with y-* and it seems to be used by a lot of folks :)

AFAIK lack of update blocks people from using new style of transports, people are getting `Error: no protocol with name: p2p-websocket-star` when trying to init with

```
{
  "config": {
    "Addresses": {
      "Swarm": ["/dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star"]
    }
  }
}
```

**Comment by pgte** [comment]
Thanks! Landed on v2.2.0.

**Pull request merged**
